(function(){
    var modules={
        "ethnicity-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/ethnicity-data.html",Table:"20009551",form_module:"ethnicity-form"},
        "ethnicity-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/ethnicity-form.html",Table:"20009551"},
        "lifestyle-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/lifestyle-data.html",Table:"20009299",form_module:"lifestyle-form"},
        "lifestyle-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/lifestyle-form.html",Table:"20009299"},
        "education-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/education-data.html",Table:"20009302",form_module:"education-form"},
        "education-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/education-form.html",Table:"20009302"},
        "medical-history-data":		{url:"$A/modules/c/cpaphdeeg-tasks/medical-history-data.html",Table:"20009300",form_module:"medical-history-form"},
        "medical-history-form":		{url:"$A/modules/c/cpaphdeeg-tasks/medical-history-form.html",Table:"20009300"},

        "file-notes-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/file-notes-data.html",Table:"20009301",form_module:"file-notes-form"},
        "file-notes-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/file-notes-form.html",Table:"20009301"},

        "adverse-event-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/adverse-event-data.html",Table:"20009304",form_module:"adverse-event-form"},
        "adverse-event-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/adverse-event-form.html",Table:"20009304"},
        
        "concomitant-medication-data":	{url:"$A/modules/c/cpaphdeeg-tasks/concomitant-medication-data.html",Table:"20009305",form_module:"concomitant-medication-form"},
        "concomitant-medication-form":	{url:"$A/modules/c/cpaphdeeg-tasks/concomitant-medication-form.html",Table:"20009305"},

        "s-visit-date-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/visit-date-data.html",Table:"20009570",form_module:"s-visit-date-form"},
        "s-visit-date-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/visit-date-form.html",Table:"20009570"},
        "s-anthropometry-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/anthropometry-data.html",Table:"20009306",form_module:"s-anthropometry-form"},
        "s-anthropometry-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/anthropometry-form.html",Table:"20009306"},
        "s-ess-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/ess-data.html",Table:"20009307",form_module:"s-ess-form"},
        "s-ess-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/ess-form.html",Table:"20009307"},     
        "s-semsa-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/semsa-data.html",Table:"20009308",form_module:"s-semsa-form"},
        "s-semsa-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/semsa-form.html",Table:"20009308"},
        "s-sleep-diary-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/sleep-diary-data.html",Table:"20009543",form_module:"s-sleep-diary-form"},
        "s-sleep-diary-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/sleep-diary-form.html",Table:"20009543"},
        "s-psg300-data":		        {url:"$A/modules/c/cpaphdeeg-tasks/psg300-data.html",Table:"20009310",form_module:"s-psg300-form"},
        "s-psg300-form":		        {url:"$A/modules/c/cpaphdeeg-tasks/psg300-form.html",Table:"20009310"},
        "s-ie-criteria-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/ie-criteria-data.html",Table:"20009571",form_module:"s-ie-criteria-form"},
        "s-ie-criteria-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/ie-criteria-form.html",Table:"20009571"},
        
        "p-n-back-data":		        {url:"$A/modules/c/cpaphdeeg-tasks/n-back-data.html",Table:"20009657",form_module:"p-n-back-form"},
        "p-n-back-form":		        {url:"$A/modules/c/cpaphdeeg-tasks/n-back-form.html",Table:"20009657"},     
        "p-stroop-color-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-color-data.html",Table:"20009660",form_module:"p-stroop-color-form"},
        "p-stroop-color-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-color-form.html",Table:"20009660"},     
        "p-stroop-text-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-text-data.html",Table:"20009659",form_module:"p-stroop-text-form"},
        "p-stroop-text-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-text-form.html",Table:"20009659"},     
        "p-letter-cancellation-data":	{url:"$A/modules/c/cpaphdeeg-tasks/letter-cancellation-data.html",Table:"20009661",form_module:"p-letter-cancellation-form"},
        "p-letter-cancellation-form":	{url:"$A/modules/c/cpaphdeeg-tasks/letter-cancellation-form.html",Table:"20009661"},     

        "bn-visit-date-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/visit-date-data.html",Table:"20009311",form_module:"bn-visit-date-form"},
        "bn-visit-date-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/visit-date-form.html",Table:"20009311"},
        "bn-anthropometry-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/anthropometry-data.html",Table:"20009312",form_module:"bn-anthropometry-form"},
        "bn-anthropometry-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/anthropometry-form.html",Table:"20009312"},
        "bn-ess-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/ess-data.html",Table:"20009313",form_module:"bn-ess-form"},
        "bn-ess-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/ess-form.html",Table:"20009313"},     
        "bn-isi-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/isi-data.html",Table:"20009315",form_module:"bn-isi-form"},
        "bn-isi-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/isi-form.html",Table:"20009315"},     
        "bn-psqi-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/psqi-data.html",Table:"20009316",form_module:"bn-psqi-form"},
        "bn-psqi-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/psqi-form.html",Table:"20009316"},     
        "bn-dass21-data":		        {url:"$A/modules/c/cpaphdeeg-tasks/dass21-data.html",Table:"20009553",form_module:"bn-dass21-form"},
        "bn-dass21-form":		        {url:"$A/modules/c/cpaphdeeg-tasks/dass21-form.html",Table:"20009553"},     
        "bn-kss-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/kss-data.html",Table:"20009314",form_module:"bn-kss-form"},
        "bn-kss-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/kss-form.html",Table:"20009314"},     
        "bn-wtar-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/wtar-data.html",Table:"20009317",form_module:"bn-wtar-form"},
        "bn-wtar-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/wtar-form.html",Table:"20009317"},     
        "bn-pvt-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/pvt-data.html",Table:"20009319",form_module:"bn-pvt-form"},
        "bn-pvt-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/pvt-form.html",Table:"20009319"},     
        "bn-n-back-data":		        {url:"$A/modules/c/cpaphdeeg-tasks/n-back-data.html",Table:"20009569",form_module:"bn-n-back-form"},
        "bn-n-back-form":		        {url:"$A/modules/c/cpaphdeeg-tasks/n-back-form.html",Table:"20009569"},     
        "bn-stroop-color-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-color-data.html",Table:"20009320",form_module:"bn-stroop-color-form"},
        "bn-stroop-color-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-color-form.html",Table:"20009320"},     
        "bn-stroop-text-data":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-text-data.html",Table:"20009309",form_module:"bn-stroop-text-form"},
        "bn-stroop-text-form":		    {url:"$A/modules/c/cpaphdeeg-tasks/stroop-text-form.html",Table:"20009309"},     
        "bn-letter-cancellation-data":	{url:"$A/modules/c/cpaphdeeg-tasks/letter-cancellation-data.html",Table:"20009321",form_module:"bn-letter-cancellation-form"},
        "bn-letter-cancellation-form":	{url:"$A/modules/c/cpaphdeeg-tasks/letter-cancellation-form.html",Table:"20009321"},     
        "bn-psg300-data":		        {url:"$A/modules/c/cpaphdeeg-tasks/psg300-data.html",Table:"20009324",form_module:"bn-psg300-form"},
        "bn-psg300-form":		        {url:"$A/modules/c/cpaphdeeg-tasks/psg300-form.html",Table:"20009324"},
        "bn-sleep-file-upload-data":		{url:"$A/modules/c/cpaphdeeg-tasks/sleep-file-upload-data.html",Table:"20009325",form_module:"bn-sleep-file-upload-form"},
        "bn-sleep-file-upload-form":		{url:"$A/modules/c/cpaphdeeg-tasks/sleep-file-upload-form.html",Table:"20009325"},
        "bn-edf-file-upload-data":		{url:"$A/modules/c/cpaphdeeg-tasks/edf-file-upload-data.html",Table:"20009326",form_module:"bn-edf-file-upload-form"},
        "bn-edf-file-upload-form":		{url:"$A/modules/c/cpaphdeeg-tasks/edf-file-upload-form.html",Table:"20009326"},
        
        "bm-kss-data":		            {url:"$A/modules/c/cpaphdeeg-tasks/kss-data.html",Table:"20009552",form_module:"bm-kss-form"},
        "bm-kss-form":		            {url:"$A/modules/c/cpaphdeeg-tasks/kss-form.html",Table:"20009552"},   
        
        "bm-finger-tapping-6-data":	    {url:"$A/modules/c/cpaphdeeg-tasks/finger-tapping-6-data.html",Table:"20010465",form_module:"bm-finger-tapping-6-form"},
        "bm-finger-tapping-6-form":	    {url:"$A/modules/c/cpaphdeeg-tasks/finger-tapping-6-form.html",Table:"20010465"},   
        
    }
    for(m in modules){$vm.module_list[m]=modules[m];}
})();
